version: '3.8'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: ldap-mock
    ports:
      - "389:389"  # LDAP порт
    environment:
      LDAP_ORGANISATION: "Example Org"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin"
    volumes:
      - ./ldap_data:/var/lib/ldap
      - ./slapd_config:/etc/ldap/slapd.d
    restart: unless-stopped

  ldap-api:
    build:
      context: .
    container_name: ldap-api
    ports:
      - "8000:8000"  # FastAPI порт
    environment:
      LDAP_MOCK_ROOT: dc=example,dc=com
      LDAP_ADMIN_USER: cn=admin
      LDAP_ADMIN_PASSWORD: admin
      LDAP_MOCK_SERVER_HOST: openldap
      LDAP_MOCK_PORT: 389
    volumes:
      - ./src:/app/src
    depends_on:
      - openldap
    restart: unless-stopped
