services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: ldap-mock
    ports:
      - "389:389"
      - "636:636" # LDAPS = LDAP + SSL/TLS
    environment:
      LDAP_ORGANISATION: "Example Org"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS_VERIFY_CLIENT: "never"
    healthcheck:
      test: ["CMD-SHELL", "pidof slapd > /dev/null && ldapsearch -x -H ldaps://localhost -b '' -s base"]
      interval: 20s
      timeout: 5s
      retries: 10
    logging:
      options:
        max-size: "50m"
    volumes:
      - ./ldap_data:/var/lib/ldap
      - ./slapd_config:/etc/ldap/slapd.d
      - ./ldap_certs:/container/service/slapd/assets/certs
    restart: unless-stopped

  ldap_web_admin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    ports:
      - "8080:80"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - openldap
    restart: unless-stopped

  ldap-api:
    build:
      context: .
    container_name: ldap-api
    ports:
      - "8000:8000"  # FastAPI порт
    environment:
      LDAP_MOCK_ROOT: dc=example,dc=com
      LDAP_ADMIN_USER: cn=admin
      LDAP_ADMIN_PASSWORD: admin
      LDAP_MOCK_SERVER_HOST: openldap
      LDAP_MOCK_PORT: 636
    volumes:
      - ./src:/app/src
      - ./ldap_certs:/container/service/slapd/assets/certs
    depends_on:
      openldap:
        condition: service_healthy
    restart: unless-stopped


volumes:
  ldap_data:
  ldap_certs:
  slapd_config: